<!ELEMENT add ANY>
<!ATTLIST add
  order CDATA #IMPLIED
  stat CDATA #IMPLIED
  val CDATA #IMPLIED
>
<!ELEMENT and ANY>
<!ELEMENT cond ANY>
<!ATTLIST cond
  addName CDATA #IMPLIED
  msgId CDATA #IMPLIED
>
<!ELEMENT def ANY>
<!ATTLIST def
  name CDATA #IMPLIED
  val CDATA #IMPLIED
>
<!ELEMENT effect ANY>
<!ATTLIST effect
  abnormal CDATA #IMPLIED
  abnormalLvl CDATA #IMPLIED
  abnormalTime CDATA #IMPLIED
  abnormalType CDATA #IMPLIED
  applyOnCaster CDATA #IMPLIED
  applyOnSummon CDATA #IMPLIED
  cancelOnAction CDATA #IMPLIED
  chance CDATA #IMPLIED
  count CDATA #IMPLIED
  displayId CDATA #IMPLIED
  displayLevel CDATA #IMPLIED
  effectPower CDATA #IMPLIED
  effectType CDATA #IMPLIED
  isOffensive CDATA #IMPLIED
  isReflectable CDATA #IMPLIED
  name CDATA #IMPLIED
  noicon CDATA #IMPLIED
  stackOrder CDATA #IMPLIED
  stackType CDATA #IMPLIED
  stackType2 CDATA #IMPLIED
  time CDATA #IMPLIED
  val CDATA #IMPLIED
>
<!ELEMENT enchant1 ANY>
<!ATTLIST enchant1
  levels CDATA #IMPLIED
  name CDATA #IMPLIED
>
<!ELEMENT enchant2 ANY>
<!ATTLIST enchant2
  levels CDATA #IMPLIED
  name CDATA #IMPLIED
>
<!ELEMENT enchant3 ANY>
<!ATTLIST enchant3
  levels CDATA #IMPLIED
  name CDATA #IMPLIED
>
<!ELEMENT enchant4 ANY>
<!ATTLIST enchant4
  levels CDATA #IMPLIED
  name CDATA #IMPLIED
>
<!ELEMENT enchant5 ANY>
<!ATTLIST enchant5
  levels CDATA #IMPLIED
  name CDATA #IMPLIED
>
<!ELEMENT enchant6 ANY>
<!ATTLIST enchant6
  levels CDATA #IMPLIED
  name CDATA #IMPLIED
>
<!ELEMENT enchant7 ANY>
<!ATTLIST enchant7
  name CDATA #IMPLIED
>
<!ELEMENT enchant8 ANY>
<!ATTLIST enchant8
  name CDATA #IMPLIED
>
<!ELEMENT for ANY>
<!ELEMENT game ANY>
<!ATTLIST game
  night CDATA #IMPLIED
>
<!ELEMENT has ANY>
<!ATTLIST has
  skill CDATA #IMPLIED
  success CDATA #IMPLIED
>
<!ELEMENT list ANY>
<!ELEMENT mul ANY>
<!ATTLIST mul
  order CDATA #IMPLIED
  stat CDATA #IMPLIED
  val CDATA #IMPLIED
>
<!ELEMENT not ANY>
<!ELEMENT or ANY>
<!ELEMENT player ANY>
<!ATTLIST player
  agathion CDATA #IMPLIED
  classId CDATA #IMPLIED
  cubic CDATA #IMPLIED
  damage CDATA #IMPLIED
  flying CDATA #IMPLIED
  flyingTransform CDATA #IMPLIED
  hasBuffId CDATA #IMPLIED
  instance_zone CDATA #IMPLIED
  maxLevel CDATA #IMPLIED
  maxPK CDATA #IMPLIED
  minLevel CDATA #IMPLIED
  moving CDATA #IMPLIED
  olympiad CDATA #IMPLIED
  percentCP CDATA #IMPLIED
  percentHP CDATA #IMPLIED
  percentMP CDATA #IMPLIED
  resting CDATA #IMPLIED
  riding CDATA #IMPLIED
  running CDATA #IMPLIED
  standing CDATA #IMPLIED
  summon_siege_golem CDATA #IMPLIED
>
<!ELEMENT set ANY>
<!ATTLIST set
  name CDATA #IMPLIED
  order CDATA #IMPLIED
  stat CDATA #IMPLIED
  val CDATA #IMPLIED
>
<!ELEMENT skill ANY>
<!ATTLIST skill
  id CDATA #IMPLIED
  levels CDATA #IMPLIED
  name CDATA #IMPLIED
>
<!ELEMENT sub ANY>
<!ATTLIST sub
  order CDATA #IMPLIED
  stat CDATA #IMPLIED
  val CDATA #IMPLIED
>
<!ELEMENT table ANY>
<!ATTLIST table
  name CDATA #IMPLIED
>
<!ELEMENT target ANY>
<!ATTLIST target
  castledoor CDATA #IMPLIED
  direction CDATA #IMPLIED
  forbiddenClassIds CDATA #IMPLIED
  hasBuff CDATA #IMPLIED
  hasBuffId CDATA #IMPLIED
  hasForbiddenSkill CDATA #IMPLIED
  mobId CDATA #IMPLIED
  npc_class CDATA #IMPLIED
  percentHP CDATA #IMPLIED
  playerRace CDATA #IMPLIED
  playerSameClan CDATA #IMPLIED
  pvp CDATA #IMPLIED
  race CDATA #IMPLIED
>
<!ELEMENT trigger ANY>
<!ATTLIST trigger
  chance CDATA #IMPLIED
  id CDATA #IMPLIED
  level CDATA #IMPLIED
  type CDATA #IMPLIED
>
<!ELEMENT triggers ANY>
<!ELEMENT using ANY>
<!ATTLIST using
  armor CDATA #IMPLIED
  kind CDATA #IMPLIED
  skill CDATA #IMPLIED
>
<!ELEMENT zone ANY>
<!ATTLIST zone
  type CDATA #IMPLIED
>